### ISSUE TITLE
status of this repo w.r.t. the maintenance and support

### ISSUE THREAD

**Issue by acharaj** [Azure/iot-edge-virtual-kubelet-provider#39]
Hi,

We would like to use this repo in a commercial deployment and wanted to know what is the status of this project w.r.t. the maintenance and support. I see that there are no new recent commits and the activities on this repo are fairly small. Therefore, we would be interested to know more on it from the Microsoft team.

Best,
Jagdish

**Comment by veyalla** [comment]
This is technical preview product which does not comes with any official support, so it is not recommended for production. Since its introduction, other OSS technologies like Flux have emerged solving a similar space. I suggest you explore those, as well as Azure Arc for Kubernetes: https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/deploy-azure-iot-edge-workloads

**Comment by acharaj** [comment]
Thanks Venkat for your quick response! In our business case, we don't want to deploy iot-edge on kubernetes. We just have a single gateway device to deploy our modules but we would like to have modules running in AKS. The translator is the best option for us because we can deploy modules to the edge device by simply writing only k8s deployment files (no need to write Azure manifest files for deploying modules on the gateway devices).

**Comment by acharaj** [comment]
I wonder why you stopped this project. At least, for our use-case scenario, it looked like the best option so far.
